name: Ansh Shah
tagline: Roboticist | Computer Vision | Deep Learning
career-objective: Hola Amigo👋
I'm Ansh Shah, an enthusiast at the intersection of mechanical engineering, physics, and robotics. I recently graduated from BITS Pilani University (Pilani Campus) with degrees in BE Mechanical Engineering and MSc Physics in May 2023. Currently, I'm immersed in the world of research as a Research Intern at the Robotics Research Center under the guidance of Professor Madhava Krishna at IIIT Hyderabad.

# My research pursuits span the realms of Deep Learning, Reinforcement Learning, and Multi-Agent SLAM, with a dash of passion for robotics hardware. My portfolio encompasses foundational projects in deep learning and computer vision. While I'm currently engrossed in mastering reinforcement learning, my excitement lies in bringing these concepts to life within real robotic systems. Notably, I've contributed to a Multi-Agent SLAM pipeline at RRC and am presently engrossed in crafting a loop closure detection module for the SLAM pipeline. Additionally, I'm actively involved in developing a differentiable local planner, further enhancing my expertise.

# Here's a glimpse of my ongoing endeavours -
# - 🔭 Presently, I'm engrossed in a Multi-Agent SLAM project tailored for Quadcopters, which involves developing a Loop Closure Detection module utilizing cutting-edge DL techniques.
# - 🛤️ I'm also deeply engaged in building a differentiable local planner, a project that adds a new dimension to my expertise and understanding.
# - 🌱 My current learning trajectory involves diving deep into Multi-Agent SLAM with a focus on pose graph optimization and its practical implementation within a Drone Swarm.
# - 👯 I'm fervently open to collaboration on projects centred around aerial robotics, driven by a shared passion for technological innovation.
# - 🤔 I'm actively seeking guidance for potential avenues in Master's programs and job/research opportunities within the captivating realm of robotics.
# - 💬 I'm always up for discussions ranging from books, sports, and philosophy to psychology, art, chess, movies, guitar, technology, and environmental studies.
# - ⚡ Fun fact - "Nothing is original. Steal like an Artist."

# Feel free to connect with me via email at anshshah3009@gmail.com or f20180917@pilani.bits-pilani.ac.in. I'm always eager to engage in meaningful conversations.

# Selected Highlights from My Project Portfolio - 
# - Multi-Agent SLAM Pipeline (VINS-MONO-GTSAM)
# - Micromouse
# - Autonomous Quadcopter
# - Quadruped Robot
# - Monocopter
# - Participation in the International Robotics Challenge at Techfest, IIT Bombay in 2019
# - Contribution to the Quadcopter for GameOfDrones at Techfest, IIT Bombay in 2019
# - Cronus (an innovative surveillance bot concept)
# - Differentiable Local Planner (Current Project)

# Looking forward to exciting possibilities and collaborations in the dynamic world of robotics.

# Looking forward to exciting possibilities and collaborations in the dynamic world of robotics.

color-theme: red # red or blue
avatar-filename: avatar.png # Change to your avatar's filename
url: anshshah3009.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: anshshah3009@gmail.com
  github: 
    visibility: true
    handle: AnshShah3009
  linkedin: 
    visibility: true
    handle: anshshah3009
  twitter: 
    visibility: true
    handle: baymax3009

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: true
  certifications: 
    label: Certifications
    visibility: true
  achievements: 
    label: Achievements
    visibility: true

navigation:
- title: About
  url: /
- title: Blog
  url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X